  deploy:
    needs: train
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download trained model
        uses: actions/download-artifact@v4
        with:
          name: trained-model
          path: .

      - name: Download metrics
        uses: actions/download-artifact@v4
        with:
          name: evaluation-metrics
          path: .

      - name: Read MSE from metrics
        id: metrics
        run: |
          echo "CURRENT_MSE=$(jq -r .mse metrics.json)" >> $GITHUB_ENV

      - name: Compare with best MSE
        run: |
          echo "Current MSE: $CURRENT_MSE"
          echo "Best MSE: $BEST_MSE"

          if (( $(echo "$CURRENT_MSE >= $BEST_MSE" | bc -l) )); then
            echo "2022BCS0102 ---- Metric did not improve"
            exit 0
          fi

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/2022bcs0102-wine-quality:latest .

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/2022bcs0102-wine-quality:latest
